# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(763, 679)
        MainWindow.setStyleSheet("/*QMainWindow {\n"
"background-image: url(:/background/icons/NRIS Zoom background.jpg);\n"
"}\n"
"\n"
"QTableWidget, QPlainTextEdit, QLineEdit, QListWidget, QPushButton, QSpinBox, QCheckBox, QComboBox {\n"
"background-color: rgba(220, 220, 220, 50);\n"
"color: rgb(220,220,220);\n"
"}\n"
"*/\n"
"\n"
"QHeaderView::section {\n"
"    /*background-color: #646464;*/\n"
"    padding: 2px;\n"
"    font-size: 14pt;\n"
"    border-style: none;\n"
"/*\n"
"    border-bottom: 1px; solid #fffff8;\n"
"    border-right: 1px; /*solid #fffff8;*/\n"
"}\n"
"\n"
"QTableWidget {\n"
"    /*background-color: rgba(44, 44, 44, 0);*/\n"
"}\n"
"\n"
"QTableWidget::item{\n"
" \n"
"\n"
" selection-background-color: rgba(255, 255, 255, 0.5);\n"
"\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    border: 1px solid #F37021;\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    border: 1px solid #F37021;\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"}\n"
"\n"
"QCalendarWidget::item:hover {\n"
"    border: 1px solid #F37021;\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    color: #F37021;\n"
"}\n"
"\n"
"\n"
"/*\n"
"QPushButton:hover\n"
"{\n"
"       background-color: rgba(255, 255, 255, 0.2);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: #F37021;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    background-color:  rgba(255, 255, 255, 0.2);\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    color: rgb(143, 23, 119);\n"
"    background-color: rgb(20, 20, 20);\n"
"}\n"
"*/")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableRoster = QtWidgets.QTableWidget(self.tab)
        self.tableRoster.setMinimumSize(QtCore.QSize(650, 250))
        self.tableRoster.setStyleSheet("QHeaderView::section {\n"
"    /*background-color: #646464;*/\n"
"    padding: 2px;\n"
"    font-size: 14pt;\n"
"    border-style: none;\n"
"/*\n"
"    border-bottom: 1px; solid #fffff8;\n"
"    border-right: 1px; /*solid #fffff8;*/\n"
"}\n"
"\n"
"QTableWidget {\n"
"    /*background-color: rgba(44, 44, 44, 0);*/\n"
"}\n"
"\n"
"QTableWidget::item{\n"
" \n"
"\n"
" selection-background-color: rgba(255, 255, 255, 0.5);\n"
"\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    border: 1px solid #F37021;\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"}")
        self.tableRoster.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableRoster.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableRoster.setObjectName("tableRoster")
        self.tableRoster.setColumnCount(0)
        self.tableRoster.setRowCount(0)
        self.tableRoster.horizontalHeader().setHighlightSections(True)
        self.verticalLayout_3.addWidget(self.tableRoster)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setVerticalSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.button_new_shift = QtWidgets.QPushButton(self.tab)
        self.button_new_shift.setObjectName("button_new_shift")
        self.gridLayout_7.addWidget(self.button_new_shift, 0, 0, 1, 3)
        self.button_swap_shifts = QtWidgets.QPushButton(self.tab)
        self.button_swap_shifts.setObjectName("button_swap_shifts")
        self.gridLayout_7.addWidget(self.button_swap_shifts, 0, 3, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 0, 7, 1, 1)
        self.button_delete_shift = QtWidgets.QPushButton(self.tab)
        self.button_delete_shift.setAutoDefault(False)
        self.button_delete_shift.setDefault(False)
        self.button_delete_shift.setFlat(False)
        self.button_delete_shift.setObjectName("button_delete_shift")
        self.gridLayout_7.addWidget(self.button_delete_shift, 0, 8, 2, 1)
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 1, 0, 2, 1)
        self.spinBox_year = QtWidgets.QSpinBox(self.tab)
        self.spinBox_year.setMinimum(1950)
        self.spinBox_year.setMaximum(2200)
        self.spinBox_year.setProperty("value", 2021)
        self.spinBox_year.setObjectName("spinBox_year")
        self.gridLayout_7.addWidget(self.spinBox_year, 1, 1, 2, 3)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 2, 4, 1, 1)
        self.checkBox_ukevakt = QtWidgets.QCheckBox(self.tab)
        self.checkBox_ukevakt.setObjectName("checkBox_ukevakt")
        self.gridLayout_7.addWidget(self.checkBox_ukevakt, 2, 8, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 3, 0, 1, 1)
        self.button_set_summary = QtWidgets.QPushButton(self.tab)
        self.button_set_summary.setObjectName("button_set_summary")
        self.gridLayout_7.addWidget(self.button_set_summary, 3, 4, 1, 1)
        self.button_reminer = QtWidgets.QPushButton(self.tab)
        self.button_reminer.setObjectName("button_reminer")
        self.gridLayout_7.addWidget(self.button_reminer, 3, 8, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 4, 0, 1, 2)
        self.button_add_attendee = QtWidgets.QPushButton(self.tab)
        self.button_add_attendee.setFlat(False)
        self.button_add_attendee.setObjectName("button_add_attendee")
        self.gridLayout_7.addWidget(self.button_add_attendee, 4, 8, 1, 1)
        self.listWidget_attendees = QtWidgets.QListWidget(self.tab)
        self.listWidget_attendees.setObjectName("listWidget_attendees")
        self.gridLayout_7.addWidget(self.listWidget_attendees, 5, 0, 2, 8)
        self.comboBox_status = QtWidgets.QComboBox(self.tab)
        self.comboBox_status.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_status.setEditable(False)
        self.comboBox_status.setObjectName("comboBox_status")
        self.comboBox_status.addItem("")
        self.comboBox_status.addItem("")
        self.comboBox_status.addItem("")
        self.comboBox_status.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_status, 5, 8, 1, 1)
        self.button_delete_attendee = QtWidgets.QPushButton(self.tab)
        self.button_delete_attendee.setObjectName("button_delete_attendee")
        self.gridLayout_7.addWidget(self.button_delete_attendee, 6, 8, 1, 1)
        self.spinBox_week = QtWidgets.QSpinBox(self.tab)
        self.spinBox_week.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBox_week.setMinimum(1)
        self.spinBox_week.setMaximum(53)
        self.spinBox_week.setProperty("value", 41)
        self.spinBox_week.setObjectName("spinBox_week")
        self.gridLayout_7.addWidget(self.spinBox_week, 3, 1, 1, 3)
        self.plainTextEdit_summary = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_summary.setMaximumSize(QtCore.QSize(16777215, 60))
        self.plainTextEdit_summary.setObjectName("plainTextEdit_summary")
        self.gridLayout_7.addWidget(self.plainTextEdit_summary, 2, 5, 2, 3)
        self.button_new_roster = QtWidgets.QPushButton(self.tab)
        self.button_new_roster.setObjectName("button_new_roster")
        self.gridLayout_7.addWidget(self.button_new_roster, 0, 6, 1, 1)
        self.comboBox_new_attendee = QtWidgets.QComboBox(self.tab)
        self.comboBox_new_attendee.setEditable(True)
        self.comboBox_new_attendee.setObjectName("comboBox_new_attendee")
        self.gridLayout_7.addWidget(self.comboBox_new_attendee, 4, 4, 1, 4)
        self.verticalLayout_3.addLayout(self.gridLayout_7)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 0, 0, 1, 1)
        self.button_save_changes = QtWidgets.QPushButton(self.tab)
        self.button_save_changes.setObjectName("button_save_changes")
        self.gridLayout_8.addWidget(self.button_save_changes, 0, 1, 1, 1)
        self.button_update = QtWidgets.QPushButton(self.tab)
        self.button_update.setObjectName("button_update")
        self.gridLayout_8.addWidget(self.button_update, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 0, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_8)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableStaff = QtWidgets.QTableWidget(self.tab_2)
        self.tableStaff.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableStaff.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableStaff.setObjectName("tableStaff")
        self.tableStaff.setColumnCount(0)
        self.tableStaff.setRowCount(0)
        self.tableStaff.horizontalHeader().setHighlightSections(True)
        self.verticalLayout_2.addWidget(self.tableStaff)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.button_new_institution = QtWidgets.QPushButton(self.tab_2)
        self.button_new_institution.setObjectName("button_new_institution")
        self.gridLayout.addWidget(self.button_new_institution, 0, 1, 1, 1)
        self.button_new_employee = QtWidgets.QPushButton(self.tab_2)
        self.button_new_employee.setObjectName("button_new_employee")
        self.gridLayout.addWidget(self.button_new_employee, 0, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 4, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)
        self.button_staff_delete = QtWidgets.QPushButton(self.tab_2)
        self.button_staff_delete.setObjectName("button_staff_delete")
        self.gridLayout.addWidget(self.button_staff_delete, 0, 6, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_staff_name = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_staff_name.setText("")
        self.lineEdit_staff_name.setObjectName("lineEdit_staff_name")
        self.gridLayout_4.addWidget(self.lineEdit_staff_name, 0, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_staff_email = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_staff_email.setObjectName("lineEdit_staff_email")
        self.gridLayout_2.addWidget(self.lineEdit_staff_email, 0, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_2, 0, 3, 1, 1)
        self.comboBox_institution = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_institution.setObjectName("comboBox_institution")
        self.gridLayout_13.addWidget(self.comboBox_institution, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_13)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.spinbox_shift_frq = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.spinbox_shift_frq.setSingleStep(0.1)
        self.spinbox_shift_frq.setProperty("value", 1.0)
        self.spinbox_shift_frq.setObjectName("spinbox_shift_frq")
        self.gridLayout_5.addWidget(self.spinbox_shift_frq, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.checkBox_sharedshifts = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_sharedshifts.setObjectName("checkBox_sharedshifts")
        self.gridLayout_6.addWidget(self.checkBox_sharedshifts, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 0, 3, 1, 1)
        self.button_save_to_employee = QtWidgets.QPushButton(self.tab_2)
        self.button_save_to_employee.setObjectName("button_save_to_employee")
        self.gridLayout_6.addWidget(self.button_save_to_employee, 0, 4, 1, 1)
        self.checkBox_does_ukevakt = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_does_ukevakt.setChecked(True)
        self.checkBox_does_ukevakt.setObjectName("checkBox_does_ukevakt")
        self.gridLayout_6.addWidget(self.checkBox_does_ukevakt, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tab_3)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)
        self.list_calendarEvents = QtWidgets.QListWidget(self.tab_3)
        self.list_calendarEvents.setMaximumSize(QtCore.QSize(16777215, 200))
        self.list_calendarEvents.setObjectName("list_calendarEvents")
        self.verticalLayout.addWidget(self.list_calendarEvents)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_new_shift.setText(_translate("MainWindow", "Add shift"))
        self.button_swap_shifts.setText(_translate("MainWindow", "Swap shifts"))
        self.button_delete_shift.setText(_translate("MainWindow", "Delete shift"))
        self.label_14.setText(_translate("MainWindow", "Year:"))
        self.label_11.setText(_translate("MainWindow", "Summary:"))
        self.checkBox_ukevakt.setText(_translate("MainWindow", "Ukevakt"))
        self.label_15.setText(_translate("MainWindow", "Week"))
        self.button_set_summary.setText(_translate("MainWindow", "Set"))
        self.button_reminer.setText(_translate("MainWindow", "Remind"))
        self.label_12.setText(_translate("MainWindow", "Attendees:"))
        self.button_add_attendee.setText(_translate("MainWindow", "Add"))
        self.comboBox_status.setItemText(0, _translate("MainWindow", "needsAction"))
        self.comboBox_status.setItemText(1, _translate("MainWindow", "accepted"))
        self.comboBox_status.setItemText(2, _translate("MainWindow", "declined"))
        self.comboBox_status.setItemText(3, _translate("MainWindow", "tentative"))
        self.button_delete_attendee.setText(_translate("MainWindow", "Remove"))
        self.button_new_roster.setText(_translate("MainWindow", "New roster"))
        self.button_save_changes.setText(_translate("MainWindow", "Save to calendar"))
        self.button_update.setText(_translate("MainWindow", "Refresh calendar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Roster"))
        self.button_new_institution.setText(_translate("MainWindow", "Add Institution"))
        self.button_new_employee.setText(_translate("MainWindow", "Add employee"))
        self.pushButton.setText(_translate("MainWindow", "Remove Institution"))
        self.button_staff_delete.setText(_translate("MainWindow", "Remove employee"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "Institution"))
        self.label_3.setText(_translate("MainWindow", "email"))
        self.label_4.setText(_translate("MainWindow", "Shift frequency"))
        self.checkBox_sharedshifts.setText(_translate("MainWindow", "Shared shifts"))
        self.button_save_to_employee.setText(_translate("MainWindow", "Save to employee"))
        self.checkBox_does_ukevakt.setText(_translate("MainWindow", "Ukevakt"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Staff"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Calendar"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))
#import icons_rc
